services:
  orchestrator:
    container_name: orchestrator
    image: ghcr.io/krinkuto11/acestream-orchestrator:v2.1.0.2
    # Configuration is now handled via the Web UI Settings panel
    # environment:
    #   - API_KEY=optional_api_key
    ports:
    - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/app/app/config
      #Set this if you want the HLS buffer to be limited by the host's memory.
      - /sys/fs/cgroup/memory.max:/host_cgroup/memory.max:ro 
    restart: on-failure
    networks:
      - aceserver

networks:
  aceserver:
    name: aceserver
    driver: bridge
