version: "3.7"

services:
    service:
        environment:
            - ENABLE_TOR=true
        volumes:
            - /home/umbrel/umbrel/app-data/aitronz-zeronet/data:/root/data
        ports:
            - 15441:15441
            - 43110:43110
        image: nofish/zeronet:latest