version: "3.8"

services:
  tor:
    image: osminogin/tor-simple
    container_name: tor-simple
    restart: always
    # This command hashes the password from the .env file and starts Tor.
    command: sh -c 'tor --HashedControlPassword "$$(tor --quiet --hash-password "$$TOR_CONTROL_PASSWD")"'
    environment:
      # Pass the password variable into the container.
      - TOR_CONTROL_PASSWD
    ports:
      - "9050:9050"
      - "9051:9051"
    volumes:
      - tor-data:/var/lib/tor
      - ${APP_DATA_DIR}/torrc:/etc/tor/torrc:ro
    networks:
      - 0net-network

  zeronet:
    image: nofish/zeronet
    container_name: zeronet
    platform: linux/amd64
    restart: unless-stopped
    # CORRECTED COMMAND: Use the supported --tor_password argument.
    command: sh -c 'python3 zeronet.py --tor_controller "tor:9051" --tor_password "$$TOR_CONTROL_PASSWD"'
    environment:
      # Pass the password variable into the container.
      - TOR_CONTROL_PASSWD
    networks:
      - 0net-network
    volumes:
      # The tor-data volume is NOT needed here, as we are not using cookies.
      - ${APP_DATA_DIR}/data:/root/data
    ports:
      - "15441:15441"
      - "43112:43110"
    depends_on:
      - tor

volumes:
  tor-data:

networks:
  0net-network: