version: '3.8'

services:
  tor:
    image: osminogin/tor-simple
    container_name: tor-simple
    restart: always
    ports:
      - "127.0.0.1:9050:9050"
    volumes:
      - tor-data:/var/lib/tor
    networks:
      - 0net-network
  
  zeronet:
    image: nofish/zeronet
    container_name: zeronet
    platform: linux/amd64
    networks:
      - 0net-network
    volumes:
      - ${APP_DATA_DIR}/data:/root/data
    ports:
      - "15441:15441"
      - "127.0.0.1:43112:43110"
    restart: unless-stopped
    depends_on:
      - tor

volumes:
  tor-data:

networks:
  0net-network: