version: "3.7"

services:
    app_proxy:
        environment:
            APP_HOST: aitronz-zeronet_zeronet_1
            APP_PORT: 43110
            PROXY_AUTH_ADD: "false"
    zeronet:
        volumes:
            - /home/umbrel/umbrel/app-data/aitronz-zeronet/data:/root/data
        ports:
            - 15441:15441
            - 43110:43110
        image: nofish/zeronet