version: "3.7"

services:
  aceserve:
    image: jopsis/aceserve:v3.2.17-fix
    container_name: aceserve
    ports:
      - "6878:6878"
      - "8621:8621"
      - "62062:62062"
    restart: unless-stopped
